#!/usr/bin/env bash

if [[ -d "${HOME}/homebrew" ]]; then
  export PATH="${HOME}/homebrew/sbin:${HOME}/homebrew/bin:${PATH}"
fi

if command -v brew > /dev/null 2>&1; then
  export PATH="$(brew --prefix)/opt/curl/bin:${PATH}"
  export PATH="$(brew --prefix)/opt/python/libexec/bin:${PATH}"
  export PATH="$(brew --prefix)/opt/fzf/install:${PATH}"
fi