#!/usr/bin/env bash

if [[ -d ${HOME}/usr/local/go/bin ]]; then
  export PATH="${HOME}/usr/local/go/bin:${PATH}"
fi

if ! command -v go > /dev/null 2>&1; then
  return
fi

export GOPATH="${HOME}/usr/local/gopath"
export GOBIN="${GOPATH}/bin"
export PATH="${GOBIN}:${PATH}"

alias pprof_memory="go tool pprof http://localhost:1080/debug/pprof/profile/heap"