#!/usr/bin/env bash

SSH_ENV="${HOME}/.ssh/agent.env"
SSH_KEY="${HOME}/.ssh/id_18824"

stop_ssh_agent() {
  if [[ -n "${SSH_AGENT_PID:-}" ]]; then
    ssh-agent -k
    rm -rf "${SSH_ENV}"
  fi
}

add_ssh_key() {
  ssh-add -t 1h -k "${SSH_KEY}"
}

start_ssh_agent() {
  stop_ssh_agent

  if [[ -e "${SSH_KEY}" ]]; then
    echo "Initializing new SSH agent..."

    touch "${SSH_ENV}"
    chmod 600 "${SSH_ENV}"

    ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    source "${SSH_ENV}" > /dev/null

    add_ssh_key
  fi
}

if [[ -f "${SSH_ENV}" ]]; then
  source "${SSH_ENV}" > /dev/null

  if [[ -n "${SSH_AGENT_PID:-}" ]]; then
    kill -0 "${SSH_AGENT_PID}" 2>/dev/null || {
      start_ssh_agent
    }
  fi
else
    start_ssh_agent
fi


# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;


