" Turnoff vi backward compatibility
set nocompatible

" Show status line
set laststatus=2

hi StatusLine ctermfg=235
hi User1 ctermfg=11 ctermbg=238
hi User2 ctermfg=232 ctermbg=154
hi User3 ctermfg=2 ctermbg=235

set statusline=
set statusline+=%1*\ \%f " Filename
set statusline+=%2*\%m" Modified
set statusline+=%*\%R " Read-Only indicator
set statusline+=%=
set statusline+=%3*\%y " Type of file
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=%1*\ %p%% " Percentage of the file
set statusline+=\ %l:%c " Line Number and Total Line
set statusline+=\  " Empty space at end


" Highlight the line currently under cursor.
set cursorline

" Show cursor position.
set ruler

" Turn on the Wild menu, better suggestion
set wildmenu

" Show line numbers on the sidebar.
set number

" No bell
set visualbell
set noerrorbells

" Search as you type character means enable incremental searching
set incsearch

" Automatically switch search to case-sensitive when search query contains an uppercase letter
set ignorecase

" Default file encoding
set encoding=utf-8

" Show current command in last line of the screen
set showcmd

" keep cursor in the same column when moving between lines
set nostartofline

" Ask for confirmation when quitting a file that has changes
set confirm

" Wrap lines
set wrap

" Spaces tab's width and indent size
set tabstop=2 shiftwidth=2
if exists(':filetype')
  filetype indent on
endif


" Show matching parenthesis
set showmatch


" Insert spaces instead of tabs
set expandtab


" Backspace behavior for corresponding to most common apps
set backspace=indent,eol,start


" Hightlight all matches of last search
set hlsearch


" Clear highlight when pressing escape
nnoremap <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[


" Keep search matches in the middle of the window.
nnoremap n nzzzv
nnoremap N Nzzzv


" Search with smart case (if uppercase provided, search is case sensitive)
set smartcase


" Omni completion
set completeopt=longest,menuone
set omnifunc=syntaxcomplete#Complete


" Auto reload file , detect when a file has been modified externally
set autoread


" Disable folding
set nofoldenable



" Disable backup files
set nobackup
set noswapfile


" Enable syntax color if exist
if exists(":syntax")
  syntax on
endif


" Change map leader if possible
if exists(":let")
  let mapleader=","
endif


" Disabling viminfo AAA
set viminfo=""


" Be lazy when redrawing screen
set lazyredraw


" Search using ctrl-p and fzf
set rtp+=/usr/local/bin/fzf
noremap <C-p> :FZF<return>


" Using ripgrep for searching and map leader with g
if executable("rg")
  set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
  nnoremap <Leader>g :silent lgrep -P<Space>
endif

" Opening quickfix automatically
if exists(':autocmd')
  autocmd QuickFixCmdPost [^l]* nested cwindow
  autocmd QuickFixCmdPost    l* nested lwindow
endif

" Save file with sudo permission
if exists(':execute')
  command W :execute ':silent w !sudo tee % > /dev/null' | :edit!
endif
