#!/usr/bin/env bash

set -euo pipefail

clean() {
  sudo rm -rf "${HOME}/.docker"

  if command -v docker > /dev/null 2>&1; then
    docker system prune -f || true

    docker rmi -f $(docker images -q) || true
    docker network rm $(docker network ls -q) || true
    docker volume rm $(docker volume ls -q) || true
  fi
}

install() {
  if ! command -v docker > /dev/null 2>&1; then
    return
  fi

  local CTOP_VERSION="0.7.3"
  local OS
  OS="$(uname -s | tr "[:upper:]" "[:lower:]")"
  local ARCH
  ARCH="$(uname -m | tr "[:upper:]" "[:lower:]")"

  if [[ ${ARCH} = "x86_64" ]]; then
    ARCH="amd64"
  fi

  curl -q -sSL --max-time 300 -o "/usr/local/bin/ctop" "https://github.com/bcicen/ctop/releases/download/v${CTOP_VERSION}/ctop-${CTOP_VERSION}-${OS}-${ARCH}"
  chmod +x +x /usr/local/bin/ctop
}