#!/usr/bin/env bash

set -euo pipefail

clean() {
  if command -v npm > /dev/null 2>&1; then
    npm cache clean --force
  fi
  rm -rf "${HOME}/.node-gyp"
  rm -rf "${HOME}/.node_repl_history"
}

install() {

  if ! command -v git > /dev/null 2>&1; then
    echo "git is required"
    exit
  fi

  local CONF_FILENAME="${CURRENT_DIR}/conf/node"
  local NODE_VERSION="latest"

  rm -rf "${HOME}/n-install"
  mkdir -p "${HOME}/usr/local/n-install/bin"
  
  curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o "${HOME}/usr/local/n-install/bin/n"
  
  chmod u+x "${HOME}/usr/local/n-install/bin/n"

  source "${CONF_FILENAME}"
  n "${NODE_VERSION}"

}
